# config.yml
# boostPower sets how powerful the rocket boost is (default: 4.0)
boostPower: 4.0

# damageShooter defines whether the shooter gets damages by their own fireworks (default: false)
damageShooter: false

# damageOthers defines whether other people (excluding the shooter) get damaged (default: true)
damageOthers: true