name: RocketJumping
version: '1.4-1.21'
main: org.twipnetwork.rocketJumping.RocketJumping
api-version: 1.21
commands:
  rocketlauncher:
    description: Reloads the RocketJumping configuration.
    usage: /<command> reload
    permission: rocketlauncher.reload
    permission-message: You do not have permission to execute this command.