name: RocketJumping
version: '1.6-1.21'
main: org.notionsmp.rocketJumping.RocketJumping
api-version: 1.21
commands:
  rocketjumping:
    description: Reloads the RocketJumping configuration.
    usage: /<command> reload
    permission: rocketjumpingo.reload
    permission-message: You do not have permission to execute this command.